version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  app:
    build: .
    command: uvicorn main:app --host ${FAST_API_APP_HOST} --port ${FAST_API_APP_PORT} --reload
    volumes:
      - .:/app
    ports:
      - "${FAST_API_APP_PORT}:8000"
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      FAST_API_APP_HOST: ${FAST_API_APP_HOST}
      FAST_API_APP_PORT: ${FAST_API_APP_PORT}
    depends_on:
      - db

volumes:
  postgres_data:
